aquality-automation/aquality-selenium-core-dotnet

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Waitings/ConditionalWait.cs

Add xml documentation to project. Fixes #21

Add xml documentation to project. Fixes #21

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Element.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/ElementFactory.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Interfaces/IElementFactory.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Interfaces/IParent.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/ElementFactoryTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/Elements/ElementFactoryExtensions.cs

Add optional parameter to Factory methods to set custom element's name

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/RelativeElementFinder.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/Locators/CalculatorWindow.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/RelativeElementFinderTests.cs

Fix RelativeElementFinder to throw the exception if the condition was not satisfied to fix #45

Fix RelativeElementFinder to throw the exception if the condition was not satisfied

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/CachedElementStateProvider.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/ElementCacheHandler.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Interfaces/IElementCacheHandler.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/CachedElementTests.cs

Fix CachedElementStateProvider to return element state regardless from element's ElementState set at constuctor
closes #50

Fix CachedElementStateProvider 

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/Startup.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Element.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/ElementActionRetrier.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/IElementActionRetrier.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/ApplicationNotStartedTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/Elements/WebElement.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/Elements/WindowElement.cs

Extract interface from ElementActionRetrier
Allow to pass ignored exceptions in constructor 
Closes #52

Extract interface from ElementActionRetrier

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/Startup.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/CachedElementStateProvider.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Element.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/ElementFactory.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/ElementFinder.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/ElementStateProvider.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/RelativeElementFinder.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Waitings/ConditionalWait.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Waitings/IConditionalWait.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/ApplicationNotStartedTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/CachedElementTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/ConditionalWaitTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/Elements/WebElement.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/ConditionalWaitTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/Elements/WindowElement.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/RelativeElementFinderTests.cs

Extract interface from ConditionalWait

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/ActionRetrier.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/ElementActionRetrier.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/IActionRetrier.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/IElementActionRetrier.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/ActionRetrierTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/ElementActionRetrierTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/LoggerTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/RetrierTests.cs
GitVersion.yml
azure-pipelines.yml

Feature/60 action retrier [+semver: major]

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/Startup.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/ActionRetrierTests.cs

register ActionRetrier in container

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/SettingsFileExtensions.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/JsonFileTests.cs

Add GetValueDictionaryOrEmpty method to use in sibling libraries for capabilities.

---

Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/CachedElementTests.cs

Ignore unstable tests

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Waitings/ConditionalWait.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Waitings/IConditionalWait.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/ConditionalWaitTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Aquality.Selenium.Core.Tests.csproj
azure-pipelines.yml

Implement asynchronous functions for Conditional wait
- add WaitForAsync that returns Task<bool>
- add WaitForTrueAsync that returns Task which may throw when awaited if the condition is not satisfied after the timeout

Feature/add async conditional waiting +semver: feature

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/AqualityServices.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Aquality.Selenium.Core.Tests.csproj
azure-pipelines.yml

- Replace hardcoded chromedriver version with WebDriverManager-based solution
- Update Microsoft.Extensions.DependencyInjection nuget packages

Enhancement: Update DI NuGet package, get web driver version programmatically in tests

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Utilities/JsonSettingsFile.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/JsonFileTests.cs

Fix type convertion for object primitive type

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/Startup.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Configurations/IVisualizationConfiguration.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Configurations/VisualizationConfiguration.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Resources/settings.json
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/IImageComparator.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/ImageComparator.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/ImageExtensions.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/ScreenshotExtensions.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/ConditionalWaitTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/ImageComparatorTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/VisualizationTests.cs

- prepare ImageExtensions and ScreenshotExtensions to be used for visualization feature
- add tests
- add ImageComparator and VisualizationConfiguration
- Stabilize flaky async conditional wait test

[Visual Testing] Image comparison

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Element.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/Interfaces/IVisualStateProvider.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/LogElementState.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Elements/VisualStateProvider.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Resources/Localization/be.json
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Resources/Localization/en.json
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Resources/Localization/ru.json
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/AqualityServices.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/CachedElementTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/Elements/Label.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/Elements/WebElement.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/FindChildElementsTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/FindElementsTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/WindowsApp/Elements/WindowElement.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/ImageComparatorTests.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/VisualStateProviderTests.cs

- Implement element's VisualStateProvider
- add Visual element's property
- add localized logging
- add tests

[Visual Testing] Implement element's VisualStateProvider

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Aquality.Selenium.Core.Tests.csproj
LICENSE

[Selenium 4] Update project dependencies +semver: breaking

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Aquality.Selenium.Core.Tests.csproj
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/LoggerTests.cs

NLog breaking changes: https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html

Update NLog to 5.0.2 and Selenium version to 4.4.0

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Aquality.Selenium.Core.Tests.csproj
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/ImageComparatorTests.cs
azure-pipelines.yml

To resolve https://github.com/aquality-automation/aquality-selenium-dotnet/issues/228

Update selenium packages to version 4.8.1

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Forms/Form.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/FormDumpTests.cs

[Visualization] Get all elements, including private from base forms, by default

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Aquality.Selenium.Core.Tests.csproj
LICENSE

+ update test package reference
+ update license year

[Enhancement] Update Selenium to v4.17.0

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/AqualityServices.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/FindElementsTests.cs

Changed ThreadLocal to AsyncLocal to be able to use async/await in the tests

[#255] changed ThreadLocal to AsyncLocal to be able to use async/await in the tests

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Applications/AqualityServices.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Applications/Browser/FindElementsTests.cs

Reverts aquality-automation/aquality-selenium-core-dotnet#119

Revert "[#255] changed ThreadLocal to AsyncLocal to be able to use async/await in the tests"

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/DumpManager.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/ImageExtensions.cs
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Visualization/VisualStateProvider.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Visualization/FormDumpTests.cs
azure-pipelines.yml

Stabilize FormDumpTests
update Sonar tasks in pipeline

[Visualization] Avoid error "Cannot take screenshot with 0 width."

---

Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.csproj
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Aquality.Selenium.Core.xml
Aquality.Selenium.Core/src/Aquality.Selenium.Core/Logging/Logger.cs
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Aquality.Selenium.Core.Tests.csproj
Aquality.Selenium.Core/tests/Aquality.Selenium.Core.Tests/Utilities/LoggerTests.cs

Update other package versions, including update to NLog v.6.0.1 
Include ConcurrentFileTarget package and update code references

Update to Selenium v.4.34.0 +semver: feature
